# Site setings
name: 'M. J. Uaje'
description: ''
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.png'
  greetings: "Hi! I'm M. J. Uaje, a sojourner eagerly waiting for the revelation of the glory of Christ and hoping to share that anticipation with you."
favicon: 'assets/images/MJUaje_ClearBG.png'
baseurl: 
production_url: https://mjuaje.com/
disqus: 'mjuaje'
mailchimp_url:
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: mjuaje.blog@gmail.com
contact_page_description: "Want to connect and further discuss any post? Need help in knowing Christ? Want to talk anything under the sun? Send me a message."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'uajejoel'
facebook: 'mjuaje'
instagram: 'uajejoel'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
